services:
  # ----- Minio TRE ------
  # -----------------------------

  minioTRE:
    image: coollabsio/minio:RELEASE.2025-04-22T22-12-26Z
    mem_limit: 512M
    mem_reservation: 256M
    cpus: 0.1
    container_name: minioTRE
    restart: always
    command: server /data --console-address ":9001"
    env_file:
      - ../../env_files/minio-shared.env
      - ../../env_files/minio-tre.env
    networks:
      - sub-net
    volumes:
      - minioTRE_data:/data
    ports:
      - 9002:9000
      - 9003:9001
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "timeout 5 sh -c 'cat < /dev/null > /dev/tcp/127.0.0.1/9000'",
        ]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
