services:
  # ----- Data Egress - UI -----
  # -------------------------------------

  DataEgressUI:
    image: harbor.ukserp.ac.uk:443/dare-trefx/control-egress-ui:3.0.3
    container_name: DataEgressUI
    restart: always
    networks:
      - sub-net
    ports:
      - 8100:8080
    depends_on:
      - DataEgressAPI
    env_file:
      - ../../env_files/egress-shared.env
      - ../../env_files/egress-ui.env
      - ../../env_files/egress-keycloak.env

  # ----- Data Egress - API -----
  # -------------------------------------

  DataEgressAPI:
    image: harbor.ukserp.ac.uk:443/dare-trefx/control-egress-api:3.0.3
    container_name: DataEgressAPI
    restart: always
    networks:
      - sub-net
    ports:
      - 8101:8080
    depends_on:
      postgresql:
        condition: service_healthy
      minioTRE:
        condition: service_healthy
    env_file:
      - ../../env_files/egress-shared.env
      - ../../env_files/egress-api.env
      - ../../env_files/egress-keycloak.env
      - ../../env_files/tre-ui-keycloak.env
