services:
  # ----- Data Egress - UI -----
  # -------------------------------------

  DataEgressUI:
    image: harbor.ukserp.ac.uk:443/dare-trefx/control-egress-ui:3.0.3
    container_name: DataEgressUI
    restart: always
    networks:
      - sub-net
    ports:
      - 8100:8080
    depends_on:
      - DataEgressAPI
    environment:
      - DemoMode=${DemoMode}
      - KeyCloakDemoMode=${KeyCloakDemoMode}
      - Serilog__SeqServerUrl=http://seq:5341
      # Data Egress Keycloak settings
      - DataEgressKeyCloakSettings__Authority=${TRE_KEYCLOAK_URL}/realms/Data-Egress/.well-known/openid-configuration
      - DataEgressKeyCloakSettings__MetadataAddress=${TRE_KEYCLOAK_URL}/realms/Data-Egress/.well-known/openid-configuration
      - DataEgressKeyCloakSettings__BaseUrl=${TRE_KEYCLOAK_URL}/realms/Data-Egress
      - DataEgressKeyCloakSettings__ClientId=Data-Egress-API
      - DataEgressKeyCloakSettings__ClientSecret=${EgressKeyCloakSecret}
      - DataEgressKeyCloakSettings__ValidAudiences=Data-Egress-UI,Data-Egress-API
      - DataEgressKeyCloakSettings__TokenExpiredAddress=${EgressKeyCloakClientUIRedirectURL}/Account/LoginAfterTokenExpired
      - DataEgressKeyCloakSettings__RedirectURL=${EgressKeyCloakClientUIRedirectURL}
      - DataEgressKeyCloakSettings__UseRedirectURL=false
      - DataEgressKeyCloakSettings__Proxy=${useproxy}
      - DataEgressKeyCloakSettings__ProxyAddresURL=${proxyurl}
      - DataEgressKeyCloakSettings__BypassProxy="DataEgressUI,treAPI,seq-tre"
      - DataEgressAPISettings__Address=http://DataEgressAPI:8080
      - MinioSettings__Url=${MINIO_TRE_UI_URL}
      - sslcookies=${sslcookies}
      - httpsRedirect=${httpsRedirect}

  # ----- Data Egress - API -----
  # -------------------------------------

  DataEgressAPI:
    image: harbor.ukserp.ac.uk:443/dare-trefx/control-egress-api:3.0.3
    container_name: DataEgressAPI
    restart: always
    networks:
      - sub-net
    ports:
      - 8101:8080
    depends_on:
      postgresql:
        condition: service_healthy
      minioTRE:
        condition: service_healthy
    environment:
      - DemoMode=${DemoMode}
      - KeyCloakDemoMode=${KeyCloakDemoMode}
      - DemoModeDefaultP=password123
      - ConnectionStrings__DefaultConnection=Server=postgres;Port=5432;Database=DATA-Egress;Include Error Detail=true;User Id=${PGLOGIN};Password=${PGPASSWORD};TrustServerCertificate=True;
      - RabbitMQ__HostAddress=rabbitmq-tre
      - Serilog__SeqServerUrl=http://seq:5341
      - TreKeyCloakSettings__Authority=${TRE_KEYCLOAK_URL}/realms/Dare-TRE/.well-known/openid-configuration
      - TreKeyCloakSettings__MetadataAddress=${TRE_KEYCLOAK_URL}/realms/Dare-TRE/.well-known/openid-configuration
      - TreKeyCloakSettings__BaseUrl=${TRE_KEYCLOAK_URL}/realms/Dare-TRE
      - TreKeyCloakSettings__ClientId=Dare-TRE-API
      - TreKeyCloakSettings__ClientSecret=${TreAPIKeyCloakSecret}
      - TreKeyCloakSettings__ValidAudiences=Dare-TRE-API,Dare-TRE-UI
      - TreKeyCloakSettings__TokenExpiredAddress=${TreAPIKeyCloakClientUIRedirectURL}/Account/LoginAfterTokenExpired
      - TreKeyCloakSettings__RedirectURL=${TreAPIKeyCloakClientUIRedirectURL}
      - TreKeyCloakSettings__UseRedirectURL=false
      - TreKeyCloakSettings__Proxy=${useproxy}
      - TreKeyCloakSettings__ProxyAddresURL=${proxyurl}
      - TreKeyCloakSettings__BypassProxy="treAPI,seq-tre"
      # Data Egress Keycloak settings?
      - DataEgressKeyCloakSettings__Authority=${TRE_KEYCLOAK_URL}/realms/Data-Egress/.well-known/openid-configuration
      - DataEgressKeyCloakSettings__MetadataAddress=${TRE_KEYCLOAK_URL}/realms/Data-Egress/.well-known/openid-configuration
      - DataEgressKeyCloakSettings__BaseUrl=${TRE_KEYCLOAK_URL}/realms/Data-Egress
      - DataEgressKeyCloakSettings__ClientId=Data-Egress-API
      - DataEgressKeyCloakSettings__ClientSecret=${EgressKeyCloakSecret}
      - DataEgressKeyCloakSettings__ValidAudiences=Data-Egress-UI,Data-Egress-API
      - DataEgressKeyCloakSettings__TokenExpiredAddress=${EgressKeyCloakClientUIRedirectURL}/Account/LoginAfterTokenExpired
      - DataEgressKeyCloakSettings__RedirectURL=${EgressKeyCloakClientUIRedirectURL}
      - DataEgressKeyCloakSettings__UseRedirectURL=false
      - DataEgressKeyCloakSettings__Proxy=${useproxy}
      - DataEgressKeyCloakSettings__ProxyAddresURL=${proxyurl}
      - DataEgressKeyCloakSettings__BypassProxy="DataEgressUI,treAPI,seq-tre"
      - MinioSettings__Url=http://minioTRE:9000
      - MinioSettings__AccessKey=${TreMinioAdminUser}
      - MinioSettings__SecretKey=${TreMinioAdminPassword}
      - MinioSettings__BucketName=testbucket
      - MinioSettings__AdminConsole=http://minioIn:9001
      - TreAPISettings__Address=http://treapi:8080
      - DataEgressAPISettings__Address=http://DataEgressAPI:8100
