services:
  # ------ TRE Agent - UI -------
  # -----------------------------------

  tre-ui:
    image: harbor.federated-analytics.ac.uk/5s-tes/agent-ui:${DEPLOYMENT_VERSION}
    container_name: treUI
    restart: always
    networks:
      - sub-net
    ports:
      - 8989:8080
    depends_on:
      - tre-api
    env_file:
      - ../../env_files/tre-ui.env
      - ../../env_files/tre-ui-keycloak.env

  # ------ TRE Agent - Web (NextJS app) -------
  # -----------------------------------
  agent-web:
    image: harbor.federated-analytics.ac.uk/5s-tes/agent-web:${DEPLOYMENT_VERSION}
    container_name: agent-web
    restart: always
    networks:
      - sub-net
    ports:
      - 3000:3000
    depends_on:
      - tre-api
    env_file:
      - ../../env_files/agent-web.env

  # ------ TRE Agent - API -------
  # -----------------------------------
  tre-api:
    image: harbor.federated-analytics.ac.uk/5s-tes/agent-api:${DEPLOYMENT_VERSION}
    container_name: treapi
    restart: always
    networks:
      - sub-net
    ports:
      - 8072:8080
    # This is the volume for the process models to make the changes in the DMN table persistent
    volumes:
      - tre_process_models:/app/ProcessModels
    depends_on:
      postgresql:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
      minioTRE:
        condition: service_healthy
      vault:
        condition: service_healthy
      orchestration:
        condition: service_healthy
    env_file:
      - ../../env_files/tre-api.env
      - ../../env_files/tre-ui-keycloak.env
      - ../../env_files/egress-keycloak.env
      - ../../env_files/zeebe.env
      - ../../env_files/vault.env

  # ----- TRE Agent - Camunda Worker -------
  # --------------------------------------------

  TRE-Camunda:
    image: harbor.federated-analytics.ac.uk/5s-tes/credentials-camunda:${DEPLOYMENT_VERSION}
    container_name: TRE-Camunda
    restart: always
    networks:
      - sub-net
    depends_on:
      orchestration:
        condition: service_healthy
      openldap:
        condition: service_healthy
      vault:
        condition: service_healthy
      postgresql:
        condition: service_healthy
    volumes:
      - tre_process_models:/app/ProcessModels
    env_file:
      - ../../env_files/tre-camunda.env
      - ../../env_files/zeebe.env
      - ../../env_files/vault.env
