services:

  # ------ RO-Crate Validator ------
  # ------------------------------------------

  flask:
    image: ${HarborFedA}/5s-tes-library/cratey-validator-fivesafes-profile:1.1.2
    container_name: ROCValidAPI
    ports:
      - "5001:5000"
    environment:
      - FLASK_APP=cratey.py
      - FLASK_ENV=development
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - redis
    networks:
      - sub-net

  celery_worker:
    image: ${HarborFedA}/5s-tes-library/cratey-validator-fivesafes-profile:1.1.2
    container_name: ROCValidWorker
    command: celery -A app.celery_worker.celery worker --loglevel=info -E
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - redis
    networks:
      - sub-net


  redis:
    image: ${HarborFedA}/5s-tes-library/redis:alpine
    ports:
      - "6379:6379"
    networks:
      - sub-net
