services:
  dind:
    image: docker:dind
    privileged: true
    command: dockerd --host=tcp://0.0.0.0:2375
    healthcheck:
      test: ["CMD", "docker", "-H", "tcp://localhost:2375", "info"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - sub-net

  tes-minio-init:
    image: minio/mc
    depends_on:
      minioTRE:
        condition: service_healthy
    entrypoint: >
      /bin/sh -c "
      mc alias set local http://minioTRE:9000 ${MinioRootUser} ${MinioRootPass} &&
      mc admin user add local ${FunnelMinioUser} ${FunnelMinioPass} &&
      mc admin policy attach local readwrite --user ${FunnelMinioUser}
      "
    networks:
      - sub-net

  funnel:
    build:
      dockerfile: Dockerfile
      context: funnel
    depends_on:
      dind:
        condition: service_healthy        
      tes-minio-init:
        condition: service_completed_successfully
    ports:
      - 8000:8000
    environment:
      - MinioKey=${FunnelMinioUser} 
      - MinioSecret=${FunnelMinioPass}
      - DOCKER_HOST=tcp://dind:2375
    networks:
      - sub-net
    volumes:
      - ./funnel:/opt/funnel/config
      - funnel_data:/opt/funnel/data

volumes:
  funnel_data:
    driver: local
