x-environment: &environment
  env_file:
    - creds.env
    - internal.env
    - routes.env
    - user.env

name: AllInOne

services:
  ######################################################
  # TRE LAYER
  ######################################################

  tre-ui:
    <<: *environment
    image: harbor.ukserp.ac.uk:443/dare-trefx/control-tre-ui:${dareVer}
    container_name: treUI
    restart: always
    networks:
      - sub-net
    ports:
      - 8989:8080
    depends_on:
      - tre-api
    environment:
      - TreKeyCloakSettings__Proxy=${useproxy}
      - TreKeyCloakSettings__ProxyAddresURL=${proxyurl}

  tre-api:
    <<: *environment
    image: harbor.ukserp.ac.uk:443/dare-trefx/control-tre-api:${dareVer}
    container_name: treapi
    restart: always
    networks:
      - sub-net
    ports:
      - 8072:8080
    # This is the volume for the process models to make the changes in the DMN table persistent
    volumes:
      - tre_process_models:/app/ProcessModels
    depends_on:
      postgresql:
        condition: service_healthy
      keycloak:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
      minioTRE:
        condition: service_healthy
      submissionAPI:
        condition: service_healthy
      vault:
        condition: service_healthy
      orchestration:
        condition: service_healthy
    environment:
      - Features__DemoAllInOne=${DemoMode}
      - Features__EphemeralCredentials=true
      - ConnectionStrings__DefaultConnection=Server=postgres;Port=5432;Database=DARE-Tre;Include Error Detail=true;User Id=${PGLOGIN};Password=${PGPASSWORD};TrustServerCertificate=True;
      - ConnectionStrings__CredentialsConnection=Server=postgres;Port=5432;Database=TRE_Credentials;Include Error Detail=true;User Id=${PGLOGIN};Password=${PGPASSWORD};TrustServerCertificate=True;
      - RabbitMQ__HostAddress=rabbitmq
      - Serilog__SeqServerUrl=http://seq:5341
      - DareAPISettings__Address=http://submissionAPI:8080
      - DataEgressAPISettings__Address=https://egressAPI:8080 
      - EnableExternalHangfire=${EnableExternalHangfire}
      - IgnoreHutchSSL=${IgnoreHutchSSL}
      - TreKeyCloakSettings__Authority=${TreKeyCloakAuthority}
      - TreKeyCloakSettings__MetadataAddress=${TreKeyCloakMetadataAddress}
      - TreKeyCloakSettings__BaseUrl=${TreKeyCloakBaseRealmAddress}
      - TreKeyCloakSettings__ClientId=${TreKeyCloakClientId}
      - TreKeyCloakSettings__ClientSecret=${TreKeyCloakSecret}
      - TreKeyCloakSettings__ValidAudiences=${TreValidAudiences}
      - TreKeyCloakSettings__Proxy=${useproxy}
      - EnableExternalHangfire=true
      - TreKeyCloakSettings__ProxyAddresURL=${proxyurl}
      - TreKeyCloakSettings__BypassProxy="treAPI,seq-tre"
      - TreKeyCloakSettings__TokenExpiredAddress=${TreKeyCloakTokenExpredAddressUI}
      - TreKeyCloakSettings__UseRedirectURL=${TreKeyCloakUseRedirect}
      - TreKeyCloakSettings__RedirectURL=${TreKeyCloakClientUIRediretURL}
      - DataEgressKeyCloakSettings__Authority=${EgressKeyCloakAuthority}
      - DataEgressKeyCloakSettings__MetadataAddress=${EgressKeyCloakMetadataAddress}
      - DataEgressKeyCloakSettings__BaseUrl=${EgressKeyCloakBaseRealmAddress}
      - DataEgressKeyCloakSettings__ClientId=${EgressKeyCloakClientID}
      - DataEgressKeyCloakSettings__ClientSecret=${EgressKeyCloakSecret}
      - DataEgressKeyCloakSettings__ValidAudiences=${EgressValidAudiences}
      - DataEgressKeyCloakSettings__Proxy=${useproxy}
      - DataEgressKeyCloakSettings__ProxyAddresURL=${proxyurl}
      - DataEgressKeyCloakSettings__BypassProxy="DataEgressUI,treAPI,seq-tre"
      - DataEgressKeyCloakSettings__TokenExpiredAddress=${EgressKeyCloakTokenExpredAddressUI}
      - DataEgressKeyCloakSettings__UseRedirectURL=${EgressKeyCloakUseRedirect}
      - DataEgressKeyCloakSettings__RedirectURL=${EgressKeyCloakClientUIRediretURL}
      - SubmissionKeyCloakSettings__Authority=${SubmissionAPIKeyCloakAuthority}
      - SubmissionKeyCloakSettings__MetadataAddress=${SubmissionAPIKeyCloakMetadataAddress}
      - SubmissionKeyCloakSettings__BaseUrl=${SubmissionAPIKeyCloakBaseRealmAddress}
      - SubmissionKeyCloakSettings__ClientId=${SubmissionAPIKeyCloakClientId}
      - SubmissionKeyCloakSettings__ClientSecret=${SubmissionAPIKeyCloakSecret}
      - SubmissionKeyCloakSettings__ValidAudiences=${SubmissionAPIValidAudiences}
      - SubmissionKeyCloakSettings__Proxy=${useproxy}
      - SubmissionKeyCloakSettings__ProxyAddresURL=${proxyurl}
      - SubmissionKeyCloakSettings__BypassProxy="treAPI,seq-tre"
      - SubmissionKeyCloakSettings__TokenExpiredAddress=${SubmissionAPIKeyCloakTokenExpredAddressUI}
      - SubmissionKeyCloakSettings__UseRedirectURL=${SubmissionAPIKeyCloakUseRedirect}
      - SubmissionKeyCloakSettings__RedirectURL=${SubmissionAPIKeyCloakClientUIRedirectURL}
      - AgentSettings__UseTESK=${UseTESK}
      - AgentSettings__UseRabbit=${UseRabbit}
      - JobSettings__scanSchedule=${scanSchedule}
      - JobSettings__syncSchedule=${syncSchedule}
      - DataEgressAPISettings__Address=http://DataEgressAPI:8080
      - AgentSettings__TESKAPIURL=${TesAPIUrl}
      - AgentSettings__TESKOutputBucketPrefix=${TesOutputBucketPrefix}
      - TreName=${TreName}
      - MinioTRESettings__Url=http://minioTRE:9000
      - MinioTRESettings__HutchURLOverride=${HutchMinioURLOverride}
      - MinioTRESettings__AccessKey=${TreMinioAdminUser}
      - MinioTRESettings__SecretKey=${TreMinioAdminPassword}
      - MinioTRESettings__AdminConsole=http://minioTRE:9001
      - MinioSubSettings__Url=${submissionMinioUrl}
      - MinioSubSettings__AccessKey=${MinioRootUser}
      - MinioSubSettings__SecretKey=${MinioRootPass}
      - MinioSubSettings__AdminConsole=${submissionMinioAdminConsole}
      - MinioSubSettings__BucketName=testbucket
      - MinioSubSettings__AWSRegion=us-east-1
      - MinioTRESettings__AWSRegion=us-east-1
      - Hutch__APIAddress=${HutchAPIAddress}
      - Hutch__DbServer=${HutchDbServer}
      - Hutch__DbName=${HutchDbName}
      - Hutch__DbPort=${HutchDbPort}
      - CredentialAPISettings__StartWebhookUrl=${CredentialAPISettingsStartWebhookUrl}
      - CredentialAPISettings__RevokeWebhookUrl=${CredentialAPISettingsRevokeWebhookUrl}
      - VaultSettings__BaseUrl=http://vault:8200
      - VaultSettings__Token=dev-only-token
      - VaultSettings__TimeoutSeconds=30
      - VaultSettings__SecretEngine=secret
      - VaultSettings__EnableRetry=true
      - VaultSettings__MaxRetryAttempts=3
      - DmnFilePath=app/ProcessModels
      - TreUISettings__Address=http://localhost:8989
      - TreAPISettings__Address=http://localhost:8072
      # Zeebe settings
      - ZeebeBootstrap__Client__GatewayAddress=orchestration:26500
      - ZeebeBootstrap__Worker__MaxJobsActive=5
      - ZeebeBootstrap__Worker__TimeoutInMilliseconds=500
      - ZeebeBootstrap__Worker__PollIntervalInMilliseconds=50
      - ZeebeBootstrap__Worker__PollingTimeoutInMilliseconds=1000
      - ZeebeBootstrap__Worker__RetryTimeoutInMilliseconds=1000

  ######################################################
  # DataEgress LAYER
  ######################################################

  DataEgressUI:
    <<: *environment
    image: harbor.ukserp.ac.uk:443/dare-trefx/control-egress-ui:${dareVer}
    container_name: DataEgressUI
    restart: always
    networks:
      - sub-net
    ports:
      - 8100:8080
    depends_on:
      - DataEgressAPI
    environment:
      - DemoMode=${DemoMode}
      - DataEgressKeyCloakSettings__Authority=${EgressKeyCloakAuthority}
      - DataEgressKeyCloakSettings__MetadataAddress=${EgressKeyCloakMetadataAddress}
      - DataEgressKeyCloakSettings__BaseUrl=${EgressKeyCloakBaseRealmAddress}
      - DataEgressKeyCloakSettings__ClientId=${EgressKeyCloakClientID}
      - DataEgressKeyCloakSettings__ClientSecret=${EgressKeyCloakSecret}
      - DataEgressKeyCloakSettings__ValidAudiences=${EgressValidAudiences}
      - DataEgressKeyCloakSettings__Proxy=${useproxy}
      - DataEgressKeyCloakSettings__ProxyAddresURL=${proxyurl}
      - DataEgressKeyCloakSettings__BypassProxy=treAPI,seq-tre
      - DataEgressKeyCloakSettings__TokenExpiredAddress=${EgressKeyCloakTokenExpredAddressUI}
      - DataEgressKeyCloakSettings__UseRedirectURL=${EgressKeyCloakUseRedirect}
      - DataEgressKeyCloakSettings__RedirectURL=${EgressKeyCloakClientUIRediretURL}
      - DataEgressAPISettings__Address=http://DataEgressAPI:8080
      - MinioSettings__Url=http://localhost:9003
      - sslcookies=${sslcookies}
      - httpsRedirect=${httpsRedirect}

  DataEgressAPI:
    <<: *environment
    image: harbor.ukserp.ac.uk:443/dare-trefx/control-egress-api:${dareVer}
    container_name: DataEgressAPI
    restart: always
    networks:
      - sub-net
    ports:
      - 8101:8080
    depends_on:
      postgresql:
        condition: service_healthy
      minioTRE:
        condition: service_healthy
      keycloak:
        condition: service_healthy
    environment:
      - DemoMode=${DemoMode}
      - ConnectionStrings__DefaultConnection=Server=postgres;Port=5432;Database=DATA-Egress;Include Error Detail=true;User Id=${PGLOGIN};Password=${PGPASSWORD};TrustServerCertificate=True;
      - RabbitMQ__HostAddress=rabbitmq-tre
      - TreKeyCloakSettings__Authority=${TreAPIKeyCloakAuthority}
      - TreKeyCloakSettings__MetadataAddress=${TreAPIKeyCloakMetadataAddress}
      - TreKeyCloakSettings__BaseUrl=${TreAPIKeyCloakBaseRealmAddress}
      - TreKeyCloakSettings__ClientId=${TreAPIKeyCloakClientId}
      - TreKeyCloakSettings__ClientSecret=${TreAPIKeyCloakSecret}
      - TreKeyCloakSettings__ValidAudiences=${TreAPIValidAudiences}
      - TreKeyCloakSettings__Proxy=${useproxy}
      - TreKeyCloakSettings__ProxyAddresURL=${proxyurl}
      - TreKeyCloakSettings__BypassProxy="treAPI,seq-tre"
      - TreKeyCloakSettings__TokenExpiredAddress=${TreAPIKeyCloakTokenExpredAddressUI}
      - TreKeyCloakSettings__UseRedirectURL=${TreKeyCloakUseRedirect}
      - TreKeyCloakSettings__RedirectURL=${TreKeyCloakClientUIRediretURL}
      - DataEgressKeyCloakSettings__Authority=${EgressKeyCloakAuthority}
      - DataEgressKeyCloakSettings__MetadataAddress=${EgressKeyCloakMetadataAddress}
      - DataEgressKeyCloakSettings__BaseUrl=${EgressKeyCloakBaseRealmAddress}
      - DataEgressKeyCloakSettings__ClientId=${EgressKeyCloakClientID}
      - DataEgressKeyCloakSettings__ClientSecret=${EgressKeyCloakSecret}
      - DataEgressKeyCloakSettings__ValidAudiences=${EgressKeyCloakClientID}
      - DataEgressKeyCloakSettings__Proxy=${useproxy}
      - DataEgressKeyCloakSettings__ProxyAddresURL=${proxyurl}
      - DataEgressKeyCloakSettings__BypassProxy="treAPI,seq-tre"
      - DataEgressKeyCloakSettings__TokenExpiredAddress=${EgressKeyCloakTokenExpredAddressUI}
      - DataEgressKeyCloakSettings__UseRedirectURL=${EgressKeyCloakUseRedirect}
      - MinioSettings__Url=http://minioTRE:9000
      - MinioSettings__AccessKey=${TreMinioAdminUser}
      - MinioSettings__SecretKey=${TreMinioAdminPassword}
      - MinioSettings__BucketName=testbucket
      - MinioSettings__AdminConsole=http://minioIn:9001
      - TreAPISettings__Address=http://treapi:8080
      - DataEgressAPISettings__Address=http://DataEgressAPI:8100

  ######################################################
  # SUBMISSION LAYER
  ######################################################

  submissionUI:
    <<: *environment
    image: harbor.ukserp.ac.uk:443/dare-trefx/control-main-ui:${dareVer}
    container_name: submissionUI
    restart: always
    networks:
      - sub-net
    ports:
      - 7220:8080
      - 8888:8080
    depends_on:
      - submissionAPI
    volumes:
      - data-protection:/root/.aspnet/DataProtection-Keys
    environment:
      - DemoMode=${DemoMode}
      - KeyCloakSettings__Proxy=false
      - DareAPISettings__Address=http://submissionAPI:8080
      - DareAPISettings_HelpAddress=http://submissionAPI:8080
      - FormIOSettings__UseInternal=true
      - SubmissionKeyCloakSettings__Proxy=${useproxy}
      - SubmissionKeyCloakSettings__ProxyAddresURL=${proxyurl}
      - SubmissionKeyCloakSettings__BypassProxy="submissionAPI,seq"
      - SubmissionKeyCloakSettings__TokenExpiredAddress=${KeyCloakTokenExpredAddressUI}
      - SubmissionKeyCloakSettings__UseRedirectURL=${KeyCloakUseRedirect}
      - SubmissionKeyCloakSettings__RedirectURL=${KeyCloakClientUIRediretURL}
      - SubmissionKeyCloakSettings__ClientSecret=${SubmissionUIClientSecret}
      - SubmissionKeyCloakSettings__AccountManagementURL=${SubmissionUIAccountManagementURL}
      - SubmissionKeyCloakSettings__BaseUrl=${SubmissionUIKeyCloakBaseUrl}
      - SuppressAntiforgery=${SuppressAntiforgery}
      - SubmissionKeyCloakSettings__MetadataAddress=${SubmissionUIKeyCloakMetadataAddress}
      - SubmissionKeyCloakSettings__Authority=${SubmissionUIKeyCloakAuthority}
      - URLSettingsFrontEnd__QueryImage=${URLSettingsFrontEndQueryImage}
      - URLSettingsFrontEnd__MinioUrl=${URLSettingsFrontEndMinioUrl}
      - sslcookies=${sslcookies}
      - httpsRedirect=${httpsRedirect}

  submissionAPI:
    <<: *environment
    image: harbor.ukserp.ac.uk:443/dare-trefx/control-main-api:${dareVer}
    container_name: submissionAPI
    restart: always
    networks:
      - sub-net
    ports:
      - 5034:8080
    volumes:
      - data-protection:/root/.aspnet/DataProtection-Keys
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 90s
      start_interval: 5s
    depends_on:
      keycloak:
        condition: service_healthy
      postgresql:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
      minioSubmission:
        condition: service_healthy
    environment:
      - DemoMode=${DemoMode}
      - ConnectionStrings__DefaultConnection=Server=postgres;Port=5432;Database=DARE-Control;Include Error Detail=true;User Id=${PGLOGIN};Password=${PGPASSWORD};TrustServerCertificate=True;
      - RabbitMQ__HostAddress=rabbitmq
      - MinioSettings__Url=http://minioSubmission:9000
      - MinioSettings__AccessKey=${MinioRootUser}
      - MinioSettings__SecretKey=${MinioRootPass}
      - MinioSettings__BucketName=testbucket
      - SuppressAntiforgery=${SuppressAntiforgery}
      - MinioSettings__AdminConsole=http://minioSubmission:9001
      - SubmissionKeyCloakSettings__Proxy=${useproxy}
      - SubmissionKeyCloakSettings__ProxyAddresURL=${proxyurl}
      - SubmissionKeyCloakSettings__BypassProxy=minioSubmission,seq
      - SubmissionKeyCloakSettings__TokenExpiredAddress=${KeyCloakTokenExpredAddressUI}
      - SubmissionKeyCloakSettings__UseRedirectURL=${KeyCloakUseRedirect}
      - SubmissionKeyCloakSettings__RedirectURL=${KeyCloakClientUIRediretURL}
      - SubmissionKeyCloakSettings__BaseUrl=${SubmissionAPIKeyCloakBaseRealmAddress}
      - SubmissionKeyCloakSettings__MetadataAddress=${SubmissionAPIKeyCloakMetadataAddress}
      - SubmissionKeyCloakSettings__Authority=${SubmissionAPIKeyCloakAuthority}
      - SubmissionKeyCloakSettings__ClientSecret=${SubmissionAPIKeyCloakSecret}
      #- SubmissionKeyCloakSettings__RemoteSignOutPath=${SubmissionRemoteSignOutPath}
      - SubmissionKeyCloakSettings__SignedOutRedirectUri=${SubmissionSignedOutRedirectUri}
      - SubmissionKeyCloakSettings__TokenRefreshSeconds=${SubmissionTokenRefreshSeconds}
      - SubmissionKeyCloakSettings__ValidAudiences=${SubmissionValidAudiences}
      - SubmissionKeyCloakSettings__Server=${SubmissionServer}
      - SubmissionKeyCloakSettings__Protocol=${SubmissionServerProtocol}
      - SubmissionKeyCloakSettings__Realm=${SubmissionRealm}
      - SubmissionKeyCloakSettings__AutoTrustKeycloakCert=${SubmissionAutoTrustKeycloakCert}
      - SubmissionKeyCloakSettings__ValidIssuer=${SubmissionValidIssuer}
      - SubmissionKeyCloakSettings__ValidAudience=${SubmissionValidAudience}

  #####################################################
  # Credentials
  #####################################################
  TRE-Camunda:
    <<: *environment
    image: harbor.ukserp.ac.uk:443/dare-trefx/control-tre-camunda:${dareVer}
    container_name: TRE-Camunda
    restart: always
    networks:
      - sub-net
    depends_on:
      orchestration:
        condition: service_healthy
      openldap:
        condition: service_healthy
      vault:
        condition: service_healthy
      postgresql:
        condition: service_healthy
    environment:
      - Logging__LogLevel__Default=Information
      - Logging__LogLevel__Microsoft.AspNetCore=Warning
      - AllowedHosts=*
      # Zeebe Bootstrap settings
      - ZeebeBootstrap__Client__GatewayAddress=orchestration:26500
      - ZeebeBootstrap__Worker__MaxJobsActive=5
      - ZeebeBootstrap__Worker__TimeoutInMilliseconds=500
      - ZeebeBootstrap__Worker__PollIntervalInMilliseconds=50
      - ZeebeBootstrap__Worker__PollingTimeoutInMilliseconds=1000
      - ZeebeBootstrap__Worker__RetryTimeoutInMilliseconds=1000
      # LDAP settings
      - LdapSettings__Host=openldap
      - LdapSettings__Port=389
      - LdapSettings__AdminDn=cn=admin,dc=camundaephemeral,dc=local
      - LdapSettings__AdminPassword=admin
      - LdapSettings__BaseDn=dc=camundaephemeral,dc=local
      - LdapSettings__UserOu=ou=Users
      - LdapSettings__UseSSL=false
      # Vault settings
      - VaultSettings__BaseUrl=http://vault:8200
      - VaultSettings__Token=dev-only-token
      - VaultSettings__TimeoutSeconds=30
      - VaultSettings__SecretEngine=secret
      - VaultSettings__EnableRetry=true
      - VaultSettings__MaxRetryAttempts=3
      - ConnectionStrings__CredentialsConnection=Server=postgres;Port=5432;Database=TRE_Credentials;Include Error Detail=true;User Id=${PGLOGIN};Password=${PGPASSWORD};
      - ConnectionStrings__TREPostgresConnection=Server=${TRE_DATA_SERVER};Port=${TRE_DATA_PORT};Database=${TRE_DATA_DATABASE};Include Error Detail=true;User Id=${TRE_DATA_USER};Password=${TRE_DATA_PASSWORD};

  ######################################################
  # Keycloak
  ######################################################
  keycloak:
    <<: *environment
    image: quay.io/keycloak/keycloak:26.0
    container_name: keycloak
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres/keycloak
      KC_DB_USERNAME: ${PGLOGIN}
      KC_DB_PASSWORD: ${PGPASSWORD}
      KC_HOSTNAME: http://localhost:8085
      KC_HOSTNAME_PORT: 8085
      KC_HOSTNAME_BACKCHANNEL_DYNAMIC: true
      #KC_HOSTNAME_STRICT: false
      #KC_HOSTNAME_STRICT_HTTPS: false
      KEYCLOAK_FRONTEND_URL: http://localhost:8085/auth 
      KC_LOG_LEVEL: info
      KC_METRICS_ENABLED: true
      KC_HEALTH_ENABLED: true
      KEYCLOAK_HEALTH_ENABLED: true
      KEYCLOAK_METRICS_ENABLED: true
      # Admin credentials
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
    networks:
      - sub-net
    command: start-dev  --import-realm #--verbose
    depends_on:
      postgresql:
        condition: service_healthy
    ports:
      - 8085:8080
    volumes:
      - ./realm-config:/opt/keycloak/data/import
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "exec 3<>/dev/tcp/0.0.0.0/9000; echo -e \"GET /health/ready HTTP/1.1\\r\\nHost: localhost\\r\\nConnection: close\\r\\n\\r\\n\" >&3; grep -q '\"status\": \"UP\"' <&3; exec 3<&- 3>&-",
        ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 90s
      start_interval: 5s

  ######################################################
  # POSTGRES
  ######################################################
  postgresql:
    <<: *environment
    image: postgres:17
    container_name: postgres
    restart: always
    environment:
      - POSTGRES_USER=${PGLOGIN}
      - POSTGRES_PASSWORD=${PGPASSWORD}
      - POSTGRES_DB=DARE-Control
    networks:
      - sub-net
    ports:
      - "5432:5432"
    volumes:
      - "postgresql_data:/var/lib/postgresql/data"
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -q -U ${PGLOGIN} -d keycloak"]

  adminer:
    <<: *environment
    image: adminer
    restart: always
    networks:
      - sub-net
    ports:
      - 8087:8080
    environment:
      - ADMINER_DEFAULT_DB_DRIVER=psql
      - ADMINER_DEFAULT_DB_HOST=postgres
      - ADMINER_DEFAULT_DB_NAME=postgres
    depends_on:
      postgresql:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "nc", "-z", "adminer", "8080"]
      timeout: 45s
      interval: 10s
      retries: 10

  ######################################################
  # Rabbit MQ
  ######################################################

  rabbitmq:
    <<: *environment
    image: rabbitmq:3-management-alpine
    container_name: "rabbitmq"
    hostname: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - rabbitdata:/var/lib/rabbitmq/
      - rabbitlogs:/var/log/rabbitmq
    networks:
      - sub-net
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 30s
      timeout: 30s
      retries: 3

  ######################################################
  # MINIO
  ######################################################
  minioSubmission:
    <<: *environment
    image: coollabsio/minio:RELEASE.2025-04-22T22-12-26Z
    container_name: minioSubmission
    restart: always
    command: server /data --console-address ":9001"
    depends_on:
      keycloak:
        condition: service_healthy
    environment:
      - MINIO_ROOT_USER=${MinioRootUser}
      - MINIO_ROOT_PASSWORD=${MinioRootPass}
      - MINIO_BROWSER_REDIRECT_URL=http://localhost:9001
      - MINIO_SERVER_URL=http://localhost:9000
      - MINIO_IDENTITY_OPENID_CONFIG_URL=${MinioIdentityConfigURL}
      - MINIO_IDENTITY_OPENID_CLIENT_ID=${MinioIdentityID}
      - MINIO_IDENTITY_OPENID_CLIENT_SECRET=${MinioOpenidSecret}
      - MINIO_IDENTITY_OPENID_DISPLAY_NAME=SSO_IDENTIFIER
      - MINIO_IDENTITY_OPENID_SCOPES=openid
      - MINIO_IDENTITY_OPENID_REDIRECT_URI_DYNAMIC=off
    networks:
      - sub-net
    volumes:
      - minioSubmission_data:/data
    ports:
      - 9000:9000
      - 9001:9001
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "timeout 5 sh -c 'cat < /dev/null > /dev/tcp/127.0.0.1/9000'",
        ]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s

  minioTRE:
    <<: *environment
    image: coollabsio/minio:RELEASE.2025-04-22T22-12-26Z
    mem_limit: 512M
    mem_reservation: 256M
    cpus: 0.1
    depends_on:
      keycloak:
        condition: service_healthy
    container_name: minioTRE
    restart: always
    command: server /data --console-address ":9001"
    environment:
      - MINIO_ROOT_USER=${MinioRootUser}
      - MINIO_ROOT_PASSWORD=${MinioRootPass}
      - MINIO_BROWSER_REDIRECT_URL=http://localhost:9003
      - MINIO_IDENTITY_OPENID_CONFIG_URL=${MinioTreIdentityConfigURL}
      - MINIO_IDENTITY_OPENID_CLIENT_ID=${MinioTreIdentityID}
      - MINIO_IDENTITY_OPENID_CLIENT_SECRET=${MinioTreOpenidSecret}
      - MINIO_IDENTITY_OPENID_DISPLAY_NAME=SSO_IDENTIFIER
      - MINIO_IDENTITY_OPENID_SCOPES=openid
      - MINIO_IDENTITY_OPENID_REDIRECT_URI_DYNAMIC=on
    networks:
      - sub-net
    volumes:
      - minioTRE_data:/data
    ports:
      - 9002:9000
      - 9003:9001
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "timeout 5 sh -c 'cat < /dev/null > /dev/tcp/127.0.0.1/9000'",
        ]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
  ######################################################
  # SEQ / Serilog
  ######################################################
  seq:
    <<: *environment
    image: datalust/seq:2025.1.14095
    container_name: seq
    restart: always
    networks:
      - sub-net
    ports:
      - 5341:80
    volumes:
      - seq_data:/data
    environment:
      - ACCEPT_EULA=Y

  ######################################################
  # CAMUNDA
  ######################################################

  orchestration: # Consolidated Zeebe + Operate + Tasklist - https://docs.camunda.io/docs/self-managed/setup/deploy/other/docker/#zeebe
    <<: *environment
    image: camunda/camunda:${CAMUNDA_VERSION}
    container_name: orchestration
    ports:
      - "26500:26500"
      - "9600:9600"
      - "8088:8080"
    environment:
      - JAVA_TOOL_OPTIONS="-XX:+PrintFlagsFinal"
    mem_limit: 1g
    restart: always
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "bash -c 'exec 3<>/dev/tcp/127.0.0.1/9600 && echo -e \"GET /actuator/health/status HTTP/1.1\r\nHost: localhost\r\n\r\n\" >&3 && head -n 1 <&3'",
        ]
      interval: 1s
      retries: 30
      start_period: 30s
    volumes:
      - zeebe:/usr/local/zeebe/data
    configs:
      - source: orchestration-config
        target: /usr/local/camunda/config/application.yaml
    networks:
      - sub-net
    depends_on:
      elasticsearch:
        condition: service_healthy

  # Camunda Connectors - executes outbound and inbound connector logic
  # Docs: https://docs.camunda.io/docs/self-managed/connectors-deployment/connectors-configuration/
  connectors:
    <<: *environment
    image: camunda/connectors-bundle:${CAMUNDA_BUNDLE_VERSION}
    container_name: connectors
    ports:
      - "8086:8080"
    environment:
      - management.endpoints.web.exposure.include=health,configprops
      - management.endpoint.health.probes.enabled=true
    # env_file: connector-secrets.txt
    mem_limit: 512m
    restart: unless-stopped
    healthcheck:
      test:
        ["CMD-SHELL", "curl -f http://localhost:8080/actuator/health/readiness"]
      interval: 30s
      timeout: 1s
      retries: 5
      start_period: 30s
    configs:
      - source: connectors-config
        target: application.yaml
    networks:
      - sub-net
    depends_on:
      orchestration:
        # Wait for orchestration service to be healthy, otherwise we get a lot of noisy logs from connection errors
        condition: service_healthy

  elasticsearch: # https://hub.docker.com/_/elasticsearch
    <<: *environment
    image: docker.elastic.co/elasticsearch/elasticsearch:${ELASTIC_VERSION}
    container_name: elasticsearch
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      # allow running with low disk space
      - cluster.routing.allocation.disk.threshold_enabled=false
      # Disable noisy deprecation logs, see https://github.com/camunda/camunda/issues/26285
      - logger.org.elasticsearch.deprecation="OFF"
    mem_limit: 4g
    restart: unless-stopped
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl -f http://localhost:9200/_cat/health | grep -q green",
        ]
      interval: 1s
      retries: 30
      start_period: 30s
      timeout: 1s
    volumes:
      - elastic:/usr/share/elasticsearch/data
    networks:
      - sub-net

  ######################################################
  # VAULT
  ######################################################
  vault:
    <<: *environment
    image: hashicorp/vault:latest
    container_name: vault
    mem_limit: 512M
    mem_reservation: 256M
    cpus: 0.2
    restart: always
    ports:
      - "8200:8200"
    environment:
      - VAULT_DEV_ROOT_TOKEN_ID=dev-only-token
      - VAULT_DEV_LISTEN_ADDRESS=0.0.0.0:8200
      - VAULT_ADDR=http://127.0.0.1:8200
    volumes:
      - vault_data:/vault/data
      - vault_logs:/vault/logs
      - ./vault-config:/vault/config:ro
    cap_add:
      - IPC_LOCK
    networks:
      - sub-net
    healthcheck:
      test: ["CMD-SHELL", "vault status || exit 1"]
      interval: 30s
      timeout: 5s
      retries: 5
      start_period: 10s
    command: ["vault", "server", "-dev", "-dev-root-token-id=dev-only-token"]

  ######################################################
  # OPENLDAP
  ######################################################
  openldap:
    <<: *environment
    image: osixia/openldap:1.5.0
    container_name: openldap
    environment:
      LDAP_LOG_LEVEL: "256"
      LDAP_ORGANISATION: "TRE Ephemeral Credentials"
      LDAP_DOMAIN: "camundaephemeral.local"
      LDAP_ADMIN_PASSWORD: "admin"
      LDAP_CONFIG_PASSWORD: "config"
      LDAP_TLS: "false"
      LDAP_ADD_LDIF_URL: "file:///container/service/slapd/assets/init.ldif"
    volumes:
      - openldap_data:/var/lib/ldap
      - openldap_config:/etc/ldap/slapd.d
      - ./ldap-init/init.ldif:/container/service/slapd/assets/init.ldif
    ports:
      - "1389:389"
      - "1636:636"
    networks:
      - sub-net
    domainname: "camundaephemeral.local"
    hostname: "ldap.camundaephemeral.local"
    tty: true
    stdin_open: true
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "ldapsearch -x -H ldap://localhost -b dc=camundaephemeral,dc=local -D 'cn=admin,dc=camundaephemeral,dc=local' -w admin",
        ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  ## Ldap initialisation to create Users OU ##
  ldap-init:
    <<: *environment
    image: osixia/openldap:1.5.0
    networks:
      - sub-net
    depends_on:
      openldap:
        condition: service_healthy
    entrypoint: >
      sh -c "
        for i in $(seq 1 30); do
          ldapsearch -x -H ldap://openldap -D 'cn=admin,dc=camundaephemeral,dc=local' -w admin -b 'dc=camundaephemeral,dc=local' && break
          sleep 2
        done
        ldapadd -x -H ldap://openldap -D 'cn=admin,dc=camundaephemeral,dc=local' -w admin -f /container/service/slapd/assets/init.ldif || true
      "
    volumes:
      - ./ldap-init/init.ldif:/container/service/slapd/assets/init.ldif

  phpldapadmin:
    <<: *environment
    image: osixia/phpldapadmin:latest
    container_name: phpldapadmin
    networks:
      - sub-net
    environment:
      PHPLDAPADMIN_LDAP_HOSTS: "openldap"
      PHPLDAPADMIN_HTTPS: "false"
    ports:
      - "8080:80"
    depends_on:
      - openldap

######################################################
# VOLUME
######################################################
volumes:
  postgresql_data:
    driver: local
  postgresql_kc:
    driver: local
  minioSubmission_data:
    driver: local
  minioTRE_data:
    driver: local
  seq_data:
    driver: local
  rabbitdata:
    driver: local
  rabbitlogs:
    driver: local
  keycloak_data:
    driver: local
  data-protection:
    driver: local
  zeebe:
    driver: local
  elastic:
    driver: local
  vault_data:
    driver: local
  vault_logs:
    driver: local
  openldap_data:
    driver: local
  openldap_config:
    driver: local
  tre_process_models:
    driver: local

######################################################
# networks
######################################################
networks:
  sub-net:
    driver: bridge

configs:
  connectors-config:
    content: |
      camunda:
        client:
          mode: self-managed
          grpc-address: http://orchestration:26500
          rest-address: http://orchestration:8080

  orchestration-config:
    content: |
      management.endpoints.configprops.show-values: always
      camunda:
        system:
          cpu-thread-count: "3"
          io-thread-count: "3"
        security:
          authentication:
            method: "basic"
            unprotectedApi: true
          authorizations:
            enabled: false
          initialization:
            users:
              - username: "demo"
                password: "demo"
                name: "Demo User"
                email: "demo@demo.com"
            defaultRoles.admin.users:
              - "demo"
        database.index.numberOfReplicas: 0 # Single node elasticsearch so we disable replication
        data:
          secondary-storage:
            type: elasticsearch
            elasticsearch:
              cluster-name: elasticsearch
              url: "http://elasticsearch:9200"
